# Generated by Django 4.2.7 on 2024-03-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='car_number')),
                ('lifting_capacity', models.PositiveIntegerField(verbose_name='lifting_capacity')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.location', verbose_name='current_location')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['number'],
            },
        ),
    ]
